//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.BillMedicines = new HashSet<BillMedicine>();
        }
    
        public int ID { get; set; }
        public int PatientID { get; set; }
        public decimal BillAmount { get; set; }
        public System.DateTime BillDate { get; set; }
        public bool BillStatus { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<BillMedicine> BillMedicines { get; set; }
    }
}
