//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillMedicine
    {
        public int ID { get; set; }
        public int MedicineID { get; set; }
        public int BilIID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
