//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PateintRecord
    {
        public PateintRecord()
        {
            this.RecordsMedicines = new HashSet<RecordsMedicine>();
        }
    
        public int ID { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public string Description { get; set; }
        public int PatientID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<RecordsMedicine> RecordsMedicines { get; set; }
    }
}
