//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.BillMedicines = new HashSet<BillMedicine>();
            this.RecordsMedicines = new HashSet<RecordsMedicine>();
        }
    
        public int ID { get; set; }
        public string MedName { get; set; }
        public Nullable<decimal> MedSellPrice { get; set; }
        public Nullable<decimal> MedPurchasePrice { get; set; }
        public Nullable<bool> IsLacking { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string MedStatus { get; set; }
        public string MedDescription { get; set; }
        public Nullable<int> MedType { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
    
        public virtual ICollection<BillMedicine> BillMedicines { get; set; }
        public virtual ICollection<RecordsMedicine> RecordsMedicines { get; set; }
    }
}
